// Cronograma regressivo completo — conteúdo extraído das seções 5.1 a 5.15
// da especificação do projeto. Cada fase é ancorada em "meses antes do
// casamento" (ou dias, nas fases finais) e populada com as tarefas sugeridas.

export type PhaseSeed = {
  name: string;
  order: number;
  monthsBeforeStart: number; // maior = mais distante do casamento
  monthsBeforeEnd: number;
  category: string;
  items: string[];
};

export const TIMELINE_PHASES: PhaseSeed[] = [
  {
    name: "Fase inicial — 24 a 30 meses antes",
    order: 1,
    monthsBeforeStart: 30,
    monthsBeforeEnd: 24,
    category: "Planejamento inicial",
    items: [
      "Definir o estilo geral do casamento",
      "Definir prioridades do casal",
      "Definir orçamento global",
      "Definir quem contribuirá financeiramente",
      "Estabelecer reserva financeira",
      "Estimar quantidade de convidados",
      "Criar lista preliminar de convidados",
      "Escolher cidade e região",
      "Avaliar casamento civil, religioso, simbólico ou combinado",
      "Escolher período do dia",
      "Escolher tipo de evento",
      "Pesquisar datas",
      "Verificar feriados e eventos concorrentes",
      "Pesquisar clima histórico",
      "Decidir se haverá destination wedding",
      "Definir necessidade de hospedagem",
      "Pesquisar espaços",
      "Pesquisar assessoria ou cerimonial",
      "Criar identidade inicial do projeto",
      "Definir regras de tomada de decisão",
      "Definir responsáveis por cada área",
      "Criar pasta de documentos",
      "Iniciar pesquisa de fornecedores principais",
    ],
  },
  {
    name: "De 20 a 24 meses antes",
    order: 2,
    monthsBeforeStart: 24,
    monthsBeforeEnd: 20,
    category: "Contratações principais",
    items: [
      "Contratar assessoria",
      "Visitar espaços",
      "Reservar local da cerimônia",
      "Reservar local da recepção",
      "Definir data definitivamente",
      "Estimar duração do evento",
      "Revisar orçamento",
      "Definir plano de pagamentos",
      "Contratar buffet, quando necessário",
      "Pesquisar decoração",
      "Pesquisar fotografia",
      "Pesquisar filmagem",
      "Pesquisar música",
      "Pesquisar celebrante",
      "Definir estilo visual",
      "Iniciar moodboard",
      "Estruturar site do casamento",
      "Avaliar hospedagem para convidados",
      "Avaliar transporte",
      "Verificar documentação necessária",
    ],
  },
  {
    name: "De 16 a 20 meses antes",
    order: 3,
    monthsBeforeStart: 20,
    monthsBeforeEnd: 16,
    category: "Fornecedores e estilo",
    items: [
      "Contratar fotografia",
      "Contratar filmagem",
      "Contratar buffet",
      "Contratar decoração",
      "Contratar música da cerimônia",
      "Contratar música da festa",
      "Contratar celebrante",
      "Definir paleta de cores",
      "Definir conceito da decoração",
      "Escolher madrinhas e padrinhos",
      "Escolher daminhas e pajens",
      "Planejar convites dos padrinhos",
      "Definir lista preliminar de presentes",
      "Iniciar pesquisa do vestido",
      "Iniciar pesquisa do traje do noivo",
      "Pesquisar beleza",
      "Pesquisar papelaria",
      "Pesquisar iluminação",
      "Pesquisar estrutura",
      "Pesquisar gerador",
      "Pesquisar mobiliário",
      "Pesquisar atrações adicionais",
    ],
  },
  {
    name: "De 12 a 16 meses antes",
    order: 4,
    monthsBeforeStart: 16,
    monthsBeforeEnd: 12,
    category: "Identidade e lua de mel",
    items: [
      "Fechar identidade visual",
      "Contratar papelaria",
      "Contratar beleza",
      "Escolher vestido",
      "Escolher traje do noivo",
      "Contratar iluminação",
      "Contratar som",
      "Contratar estrutura necessária",
      "Reservar hospedagem do casal",
      "Reservar bloqueio de quartos",
      "Criar site do casamento",
      "Cadastrar informações iniciais no site",
      "Definir lista de presentes",
      "Decidir sobre lua de mel",
      "Iniciar planejamento da lua de mel",
      "Revisar convidados",
      "Separar convidados por grupos",
      "Definir regras para acompanhantes",
      "Planejar save the date",
      "Revisar contratos",
      "Criar planejamento de alimentação e bebidas",
      "Avaliar restrições alimentares",
    ],
  },
  {
    name: "De 9 a 12 meses antes",
    order: 5,
    monthsBeforeStart: 12,
    monthsBeforeEnd: 9,
    category: "Padrinhos e civil",
    items: [
      "Enviar save the date",
      "Confirmar padrinhos",
      "Confirmar crianças da cerimônia",
      "Definir roupas dos padrinhos",
      "Definir roupas das madrinhas",
      "Escolher acessórios",
      "Escolher sapatos",
      "Definir alianças",
      "Contratar doces",
      "Contratar bolo",
      "Contratar bar",
      "Contratar bebidas",
      "Contratar transporte",
      "Contratar hospedagem, quando aplicável",
      "Contratar cabine ou atração",
      "Definir lembranças",
      "Iniciar lista definitiva de convidados",
      "Organizar endereços e contatos",
      "Revisar documentos do casamento civil",
      "Verificar curso de noivos, proclamas ou exigências religiosas",
      "Definir roteiro preliminar da cerimônia",
      "Definir repertório inicial",
    ],
  },
  {
    name: "De 6 a 9 meses antes",
    order: 6,
    monthsBeforeStart: 9,
    monthsBeforeEnd: 6,
    category: "Cardápio e viagem",
    items: [
      "Fechar cardápio",
      "Realizar degustação",
      "Definir bolo",
      "Definir doces",
      "Definir bebidas",
      "Definir decoração detalhada",
      "Definir flores",
      "Definir mobiliário",
      "Definir mesa do bolo",
      "Definir cerimônia",
      "Escolher músicas",
      "Escolher leituras",
      "Escolher votos",
      "Escolher participantes",
      "Contratar ou confirmar lua de mel",
      "Verificar passaportes",
      "Verificar vistos",
      "Verificar vacinas",
      "Contratar seguro viagem",
      "Encomendar convites",
      "Revisar site",
      "Preparar lista de envio",
      "Fazer provas de roupas",
      "Definir chá de panela, chá bar ou outros eventos",
      "Organizar lista de presentes",
      "Definir logística de montagem",
      "Contratar segurança",
      "Contratar limpeza",
      "Contratar brigadistas ou equipe de emergência, se necessário",
      "Definir plano para chuva",
    ],
  },
  {
    name: "De 4 a 6 meses antes",
    order: 7,
    monthsBeforeStart: 6,
    monthsBeforeEnd: 4,
    category: "Convites e roteiro",
    items: [
      "Enviar convites",
      "Abrir confirmação de presença",
      "Acompanhar entregas",
      "Registrar convites devolvidos",
      "Definir prazo de RSVP",
      "Contratar lembranças",
      "Contratar itens personalizados",
      "Confirmar transporte",
      "Confirmar hospedagem",
      "Organizar lista de músicas",
      "Organizar músicas proibidas",
      "Escolher entrada dos padrinhos",
      "Escolher entrada do casal",
      "Escolher primeira dança",
      "Definir abertura da pista",
      "Definir surpresas",
      "Finalizar roteiro da cerimônia",
      "Finalizar roteiro da recepção",
      "Revisar cardápio",
      "Revisar quantidades",
      "Fazer nova prova do vestido",
      "Fazer prova do traje",
      "Testar cabelo e maquiagem",
      "Solicitar documentação civil",
      "Verificar taxas e prazos cartorários",
      "Realizar reuniões com fornecedores",
      "Iniciar plano de mesas",
    ],
  },
  {
    name: "De 3 a 4 meses antes",
    order: 8,
    monthsBeforeStart: 4,
    monthsBeforeEnd: 3,
    category: "RSVP e revisões",
    items: [
      "Acompanhar RSVP",
      "Cobrar convidados pendentes",
      "Confirmar acompanhantes",
      "Confirmar crianças",
      "Registrar restrições alimentares",
      "Revisar quantidade de convidados",
      "Organizar mesas",
      "Definir lugares prioritários",
      "Revisar decoração",
      "Revisar iluminação",
      "Revisar som",
      "Revisar cronograma de montagem",
      "Definir cronograma do dia",
      "Definir responsáveis por emergências",
      "Preparar kit banheiro",
      "Preparar kit emergência",
      "Preparar kit do casal",
      "Preparar objetos pessoais",
      "Organizar documentos da lua de mel",
      "Confirmar fornecedores",
      "Revisar contratos e saldos",
      "Verificar pagamentos finais",
      "Conferir alianças",
      "Definir textos de agradecimento",
      "Definir lembranças especiais",
      "Organizar despedidas, chás ou encontros",
    ],
  },
  {
    name: "De 2 a 3 meses antes",
    order: 9,
    monthsBeforeStart: 3,
    monthsBeforeEnd: 2,
    category: "Fechamentos finais",
    items: [
      "Encerrar confirmação principal",
      "Telefonar para convidados sem resposta",
      "Confirmar lista final aproximada",
      "Enviar informações de hospedagem",
      "Enviar informações de transporte",
      "Enviar orientações de traje",
      "Enviar localização e horários",
      "Finalizar mapa de mesas",
      "Finalizar cartões de lugar",
      "Finalizar menus",
      "Finalizar placas",
      "Finalizar identidade visual aplicada",
      "Fazer prova final de roupas",
      "Amaciar sapatos",
      "Confirmar repertório",
      "Confirmar cerimônia",
      "Confirmar votos",
      "Confirmar discursos",
      "Confirmar padrinhos",
      "Confirmar daminhas e pajens",
      "Verificar plano de chuva",
      "Revisar quantidades de bebidas",
      "Revisar duração do evento",
      "Confirmar equipe de montagem",
      "Confirmar equipe de desmontagem",
    ],
  },
  {
    name: "De 30 a 60 dias antes",
    order: 10,
    monthsBeforeStart: 2,
    monthsBeforeEnd: 1,
    category: "Últimos preparativos",
    items: [
      "Fechar número de convidados",
      "Informar quantidade ao buffet",
      "Informar restrições alimentares",
      "Fechar mesas",
      "Imprimir materiais",
      "Pagar fornecedores conforme contrato",
      "Reunir comprovantes",
      "Preparar envelopes de pagamentos",
      "Confirmar horários de chegada",
      "Confirmar contatos de emergência",
      "Confirmar decoração",
      "Confirmar flores",
      "Confirmar bolo",
      "Confirmar doces",
      "Confirmar bebidas",
      "Confirmar transporte",
      "Confirmar hospedagem",
      "Confirmar lua de mel",
      "Organizar malas",
      "Realizar ensaio",
      "Realizar reunião final com assessoria",
      "Revisar roteiro minuto a minuto",
      "Revisar previsão do tempo",
      "Revisar plano de contingência",
      "Conferir documentação civil e religiosa",
      "Providenciar procurações ou autorizações, se aplicável",
    ],
  },
  {
    name: "De 15 a 30 dias antes",
    order: 11,
    monthsBeforeStart: 1,
    monthsBeforeEnd: 0.5,
    category: "Reta final",
    items: [
      "Confirmar presença novamente, quando necessário",
      "Revisar desistências",
      "Substituir convidados, se permitido",
      "Enviar informações finais",
      "Finalizar lista de fornecedores",
      "Compartilhar contatos com assessoria",
      "Compartilhar cronograma",
      "Separar documentos",
      "Separar alianças",
      "Separar roupas",
      "Separar acessórios",
      "Separar itens da cerimônia",
      "Separar itens da festa",
      "Preparar kit de emergência",
      "Preparar kit de higiene",
      "Preparar remédios de uso pessoal",
      "Preparar brindes e lembranças",
      "Conferir pagamentos",
      "Conferir notas fiscais",
      "Conferir contratos",
      "Definir responsável pelos presentes",
      "Definir responsável pelos pertences",
      "Definir responsável pelos documentos",
      "Definir responsável pelas alianças",
    ],
  },
  {
    name: "Última semana",
    order: 12,
    monthsBeforeStart: 0.23, // ~7 dias
    monthsBeforeEnd: 0.03,
    category: "Última semana",
    items: [
      "Confirmar todos os fornecedores",
      "Revisar horários",
      "Revisar endereços",
      "Revisar cronograma",
      "Revisar contatos",
      "Conferir previsão do tempo",
      "Ativar plano de chuva, se necessário",
      "Conferir roupas",
      "Conferir acessórios",
      "Conferir malas",
      "Conferir documentos",
      "Conferir alianças",
      "Conferir votos",
      "Conferir pagamentos",
      "Entregar itens à assessoria",
      "Realizar manicure, cabelo e cuidados pessoais",
      "Descansar",
      "Organizar alimentação e hidratação",
      "Evitar novos procedimentos estéticos arriscados",
      "Preparar comunicação de emergência",
      "Confirmar transporte do casal",
      "Confirmar transporte de familiares",
      "Confirmar check-in da hospedagem",
    ],
  },
  {
    name: "Dia anterior",
    order: 13,
    monthsBeforeStart: 0.03,
    monthsBeforeEnd: 0,
    category: "Véspera",
    items: [
      "Conferir checklist final",
      "Entregar alianças ao responsável",
      "Entregar documentos ao responsável",
      "Entregar pagamentos pendentes",
      "Deixar roupas preparadas",
      "Carregar celulares",
      "Separar carregadores",
      "Revisar horário de despertar",
      "Revisar transporte",
      "Hidratar-se",
      "Realizar refeição adequada",
      "Evitar alterações de última hora",
      "Confirmar plano de chuva",
      "Descansar",
    ],
  },
  {
    name: "Dia do casamento",
    order: 14,
    monthsBeforeStart: 0,
    monthsBeforeEnd: 0,
    category: "Dia do casamento",
    items: [
      "Montagem e testes técnicos",
      "Chegada de fornecedores",
      "Horários de beleza",
      "Horários de alimentação",
      "Chegada de familiares e padrinhos",
      "Início da cerimônia",
      "Troca de alianças e assinaturas",
      "Fotos após a cerimônia",
      "Recepção e discursos",
      "Jantar",
      "Corte do bolo",
      "Primeira dança e abertura da pista",
      "Entrega de lembranças",
      "Encerramento e desmontagem",
      "Retirada de presentes e itens pessoais",
    ],
  },
  {
    name: "Pós-casamento",
    order: 15,
    monthsBeforeStart: -0.1,
    monthsBeforeEnd: -2,
    category: "Pós-casamento",
    items: [
      "Conferir devolução de materiais",
      "Conferir itens alugados",
      "Conferir cauções",
      "Pagar saldos pendentes",
      "Revisar cobranças",
      "Registrar despesas finais",
      "Guardar documentos",
      "Enviar agradecimentos",
      "Agradecer fornecedores",
      "Avaliar fornecedores",
      "Organizar presentes",
      "Controlar trocas",
      "Organizar fotos",
      "Selecionar álbum",
      "Selecionar vídeo",
      "Guardar vestido",
      "Devolver traje",
      "Preservar buquê",
      "Atualizar documentos pessoais, se aplicável",
      "Encerrar site do casamento",
      "Baixar lista de presentes",
      "Revisar orçamento final",
      "Registrar aprendizados",
      "Acompanhar entregas de fotos e vídeos",
    ],
  },
];
